### ISSUE TITLE
Installation for PostgreSQL installed from package. 

### ISSUE THREAD

**Issue by tahitihat** [segasai/pg_healpix#2]
The install instructions may not be sufficient for users who have installed PostgreSQL from a package. For example, when I run make, I get the error 

```
pg_healpix.c:31:10: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
compilation terminated.
<builtin>: recipe for target 'pg_healpix.o' failed
make: *** [pg_healpix.o] Error 1
```

This is because the postgres-related include directives in pg_healpix.c reference third party headers from the PostgreSQL source code distribution (see below). 

```
#include "postgres.h"
#include "executor/spi.h"
#include "utils/lsyscache.h"
#include "utils/array.h"
#include "catalog/pg_type.h"
#include "fmgr.h
```

Users who installed PostgreSQL with a package like apt-get will not have the source code, including those header files, on their machine. In this case, it's necessary to [manually download](https://www.postgresql.org/ftp/source/) the postgresql/src/include directory for the installed version of PostgreSQL and move everything to the right location. I think another option is to install the server side development package `postgresql-server-dev-<postgres version.`, but I did not pursue this myself. 

I suggest including some reference to this in the install instructions. 

Additionally: users likely need to run `\i pg_healpix--1.0.sql` from the psql client, not `\i pg_healpix.sql`

**Comment by segasai** [comment]
Thanks 
The right strategy is to have the relevant development packages postgres-server-dev etc. I'll add it to the readme.
